import type { ExperienceItem } from "../types";

export const experienceItems: ExperienceItem[] = [
  {
    id: "exp-verity",
    role: "Founder & CEO",
    company: "Verity Protect | Secure Screen Calling",
    period: "2026 - Present",
    startYear: 2026,
    summary:
      "Leading Verity Protect, a call-screening platform that filters unknown callers through a dedicated Verity number so families stay protected without interrupting trusted contacts.",
    highlights: [
      "Solely owned research, brand strategy, marketing, advertising, and UI/UX/product design for the 7-day free trial and subsequent monthly Apple billing flow so the service felt cohesive from discovery through signup.",
      "Built the partnership program, outreach, and operational tooling that supports facilities, families, and alerting while still handling every piece of growth and support solo.",
    ],
    tags: ["Product", "Ownership", "Growth"],
    relatedProjectIds: ["verity-protect"],
    relatedLinks: [
      { label: "Website", url: "https://verityprotect.com/" },
      { label: "Apple App Store", url: "https://apps.apple.com/app/verity-protect/id1703802527" },
    ],
  },
  {
    id: "exp-pgc-product",
    role: "Product Engineer (Web & Mobile)",
    company: "Packanack Golf Club",
    period: "2024 - Present",
    startYear: 2024,
    summary: "Own the club's web and mobile product stack used by roughly 300 members and 10 staff.",
    highlights: [
      "Designed, built, and maintain the website and app across bookings, food ordering, events, course updates, and live club operations.",
      "Handle the stack end to end, including UX/UI, frontend, backend, deployment, SEO, content updates, and ongoing performance and reliability work.",
    ],
    tags: ["Product", "Web App", "Operations"],
    relatedProjectIds: ["pgc-website", "pgc-app"],
  },
  {
    id: "exp-chc",
    role: "Volunteer Golf Instructor",
    company: "Christians Health Center",
    period: "2023 - Present",
    startYear: 2023,
    summary: "Volunteer golf instructor helping older adults build confidence and enjoyment through patient coaching.",
    highlights: [
      "Lead one-on-one and small-group simulator sessions whenever I am home from college, working with many different learners over time.",
      "Focus on instruction, encouragement, and adaptability so older students can progress at their own pace in a supportive environment.",
    ],
    tags: ["Coaching", "Community", "Wellness"],
  },
  {
    id: "exp-rsp",
    role: "Photo Editor & Layout Intern",
    company: "RSP Media",
    period: "2022 - Present",
    startYear: 2022,
    summary: "Produce jewelry photography, retouching, and editorial layout assets for brand and magazine work.",
    highlights: [
      "Capture and edit product imagery for jewelry brands, focusing on lighting, angles, detail, and polished color correction.",
      "Prepare editorial and marketing assets for magazine layouts and campaign deliverables, keeping visuals production ready across print and digital.",
    ],
    tags: ["Photography", "Editing", "Layout"],
    relatedLinks: [{ label: "RSP Media", url: "https://rspmedia.format.com/" }],
  },
  {
    id: "exp-pack",
    role: "Club Web Manager & Assistant",
    company: "Packanack Golf Club",
    period: "2022 - Present",
    startYear: 2022,
    summary: "Maintain the club website while supporting day-to-day member communication and golf shop operations.",
    highlights: [
      "Update site content, SEO, imagery, and seasonal information so the public-facing experience stays current and accurate.",
      "Support golf shop workflows, member communication, and live event logistics while staying responsive to daily team needs.",
    ],
    tags: ["Operations", "Hospitality", "Support"],
    relatedProjectIds: ["pgc-website"],
  },
  {
    id: "exp-sage",
    role: "Founder & Digital Manager",
    company: "SageAIO",
    period: "2021 - 2023",
    startYear: 2021,
    summary: "Founded a COVID-era retail automation startup spanning product, engineering, design, and growth.",
    highlights: [
      "Built a retail automation app with Go, Python, and Vue.js that helped users track restocks and buy fast-moving out-of-stock items as they returned.",
      "Led a team of about six while handling UI/UX, media, PR, and partnerships, growing the brand to 10k+ followers and supporting users who often reported around $1k/month in resale income.",
    ],
    tags: ["Leadership", "UI/UX", "Growth"],
    relatedProjectIds: ["sageaio"],
  },
  {
    id: "exp-mon",
    role: "BFA Design & Animation",
    company: "Monmouth University",
    period: "2023 - Present",
    startYear: 2023,
    summary: "Studying design and animation with a focus on visual systems, motion, and digital product work.",
    highlights: [
      "Maintained a 3.8 GPA while focusing on graphic and interactive design, web, and motion-based work.",
      "Collaborated with CS students on interactive prototypes and had work featured in Monmouth Review Vol. 67 and 68.",
    ],
    tags: ["Education", "Design", "Web"],
  },
];
