import type { ExperienceItem } from "../types";

export const experienceItems: ExperienceItem[] = [
  {
    id: "exp-pgc-product",
    role: "Product Engineer (Web & Mobile)",
    company: "Packanack Golf Club",
    period: "2024 - Present",
    startYear: 2024,
    summary: "Design and maintain member-facing web and mobile products used daily by golfers and staff.",
    highlights: [
      "Built the public site and internal app flows for bookings, ordering, and live club operations.",
      "Ship iterative UX, reliability, and performance improvements to keep both products fast and dependable.",
    ],
    tags: ["Product", "Web App", "Operations"],
    relatedProjectIds: ["pgc-website", "pgc-app"],
  },
  {
    id: "exp-chc",
    role: "Volunteer Golf Instructor",
    company: "Christians Health Center",
    period: "2023 - Present",
    startYear: 2023,
    summary: "Coach seniors through confidence-first golf instruction that balances structure and encouragement.",
    highlights: [
      "Lead one-on-one and small-group simulator sessions in focused 1-2 hour coaching blocks.",
      "Adapt drills to each student and create a supportive environment that keeps people progressing.",
    ],
    tags: ["Coaching", "Community", "Wellness"],
  },
  {
    id: "exp-rsp",
    role: "Photo Editor & Layout Intern",
    company: "RSP Media",
    period: "2022 - Present",
    startYear: 2022,
    summary: "Produce campaign-ready jewelry visuals and layout assets across digital and print deliverables.",
    highlights: [
      "Capture and edit product photography with controlled lighting, angle studies, and color correction.",
      "Support marketing and magazine layouts with polished image prep and production-ready exports.",
    ],
    tags: ["Photography", "Editing", "Layout"],
    relatedLinks: [{ label: "RSP Media", url: "https://rspmedia.format.com/" }],
  },
  {
    id: "exp-pack",
    role: "Club Web Manager & Assistant",
    company: "Packanack Golf Club",
    period: "2022 - Present",
    startYear: 2022,
    summary: "Support day-to-day club operations and member communication with consistent execution.",
    highlights: [
      "Run open/close routines and front-of-house workflows across high-traffic golf shop hours.",
      "Coordinate member updates and logistics while staying responsive to live team needs.",
    ],
    tags: ["Operations", "Hospitality", "Support"],
    relatedProjectIds: ["pgc-website"],
  },
  {
    id: "exp-sage",
    role: "Founder & Digital Manager",
    company: "SageAIO",
    period: "2021 - 2023",
    startYear: 2021,
    summary: "Led product, design, and digital growth for an early-stage startup.",
    highlights: [
      "Managed a distributed team of developers and designers through iterative delivery cycles.",
      "Directed UI/UX and social strategy, building audience engagement to 10k+ followers.",
    ],
    tags: ["Leadership", "UI/UX", "Growth"],
    relatedProjectIds: ["sageaio"],
  },
  {
    id: "exp-mon",
    role: "BFA Design & Animation",
    company: "Monmouth University",
    period: "2023 - Present",
    startYear: 2023,
    summary: "Built a design foundation in visual systems, motion, and interactive product work.",
    highlights: [
      "Maintained a 3.8 GPA with concentration in graphic + interactive design and web development.",
      "Built prototypes with CS collaborators and had selected work featured in the Monmouth Review.",
    ],
    tags: ["Education", "Design", "Web"],
  },
];
